name: Build OnePlus 12 A15 Kernel
on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
    steps:
    - name: Set swap to 10G
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - name: Setup build kernel environment
      run: |
        echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%y%m%d")" >> $GITHUB_ENV
        sudo apt-get update
        sudo apt-get install git dwarves libelf-dev ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python3 repo
        mkdir -p $GITHUB_WORKSPACE/builds

    - name: Download patch source
      run: |
        cd ./builds
        ROOT_DIR="OP12-A15-$(date +'%Y-%m-%d-%I-%M-%p')-release"
        mkdir -p "$ROOT_DIR"
        cd "$ROOT_DIR"
        git clone https://github.com/TheWildJames/AnyKernel3.git -b android14-5.15
        git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-6.1
        git clone https://github.com/TheWildJames/kernel_patches.git

    - name: Download kernel
      run: |
        mkdir oneplus12_v
        cd ./oneplus12_v
        repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8650 -m oneplus12_v.xml
        repo sync -j$(nproc)

        rm -rf ./kernel_platform/common/android/abi_gki_protected_exports_*
        
    - name: add ksu
      run: |
       cd ./kernel_platform
       curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU/next/kernel/setup.sh" | bash -s next
       cd ./KernelSU-Next/kernel
       sed -i 's/ccflags-y += -DKSU_VERSION=16/ccflags-y += -DKSU_VERSION=12113/' ./Makefile
       cd ../../
       cp ../../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU-Next/
       cp ../../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch ./common/
       cp ../../susfs4ksu/kernel_patches/fs/susfs.c ./common/fs/
       cp ../../susfs4ksu/kernel_patches/include/linux/susfs.h ./common/include/linux/
       cd ./KernelSU-Next/
       patch -p1 < 10_enable_susfs_for_ksu.patch
       cd ../common
       patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch || true
       cp ../../kernel_patches/69_hide_stuff.patch ./
       patch -p1 -F 3 < 69_hide_stuff.patch || true
       sed -i '/obj-\$(CONFIG_KSU_SUSFS_SUS_SU) += sus_su.o/d' ./fs/Makefile
       cd ..
       cp ../kernel_patches/selinux.c_fix.patch ./
       patch -p1 -F 3 < selinux.c_fix.patch
       cp ../kernel_patches/apk_sign.c_fix.patch ./
       patch -p1 -F 3 < apk_sign.c_fix.patch
       cp ../kernel_patches/Makefile_fix.patch ./
       patch -p1 --fuzz=3 < ./Makefile_fix.patch
       echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
       echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
       echo "CONFIG_KSU_SUSFS_SUS_SU=y" >> ./common/arch/arm64/configs/gki_defconfig
       cd ..
        
    - name: Build kernel
      run: |
        sed -i '2s/check_defconfig//' ./kernel_platform/common/build.config.gki
        ./kernel_platform/oplus/build/oplus_build_kernel.sh pineapple gki
        cp ./out/dist/Image ../AnyKernel3/Image
        cd ../AnyKernel3
        ZIP_NAME="Anykernel3-OP-A15-android14-6.1-KernelSU-SUSFS-$(date +'%Y-%m-%d-%H-%M-%S').zip"
        echo "Creating zip file $ZIP_NAME..."
        zip -r "../$ZIP_NAME" ./*
    - name: Upload Image
      uses: actions/upload-artifact@v4
      with:
        name: Image
        path: builds/AnyKernel3/*zip
